repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npm run lint
        language: node
        types: [javascript, jsx, typescript, tsx]
        working_directory: frontend
        pass_filenames: false
