# Generated by Django 4.2.30 on 2026-05-14 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("screening", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="assigned_questionnaires",
            field=models.ManyToManyField(blank=True, to="screening.questionnaire"),
        ),
        migrations.AddField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="screeningresponse",
            name="score",
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("psychiatrist", "Psychiatrist"), ("hr", "HR Admin")],
                        default="hr",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GradingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Psychiatrist-defined grading rules. Example: {"grade_boundaries": {"A": 10, "B": 20, "C": 30, "D": 40, "F": 100}, "composite_formula": "average", "scale_weights": {"PHQ-9": 1.0, "GAD-7": 1.0}}',
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_config",
                        to="screening.company",
                    ),
                ),
            ],
        ),
    ]
