# Generated by Django 4.2.30 on 2026-05-14 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("screening", "0002_company_assigned_questionnaires_company_is_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["name"]},
        ),
    ]
